#pragma once

#include <crunch/error.hpp>
#include <crunch/format.hpp>
#include <crunch/sequences.hpp>

#include <cstddef>
#include <cstdint>
#include <vector>

namespace crunch {

// entropy state shared by a frame's compressed blocks
struct block_context {
  huffman_table literals_table;
  sequence_tables tables;
  repeat_offsets recent;
  bool have_literals_table = false;
  const std::byte *history = nullptr; // dictionary content
  std::size_t history_size = 0;
  std::uint64_t window = 0;        // Window_Size, caps match reach
  std::vector<std::byte> literals; // scratch, sized on first use
};

void seed_block_context(block_context &context, const dictionary &dict);

// src spans one block's content; dst is the frame output so far and
// written advances past the regenerated bytes
error decode_compressed_block(const std::byte *src, std::size_t size,
                              block_context &context, std::byte *dst,
                              std::size_t dst_capacity, std::size_t &written,
                              std::uint64_t block_max);

} // namespace crunch
